# Generated by Django 5.2.8 on 2025-12-04 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IplApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='franchise',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='franchise_logos/'),
        ),
    ]
