# Generated by Django 5.2.8 on 2025-12-06 03:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IplApp', '0003_player'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='franchise',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='IplApp.franchise'),
            preserve_default=False,
        ),
    ]
