# Generated by Django 5.2.8 on 2025-12-08 03:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IplApp', '0004_player_franchise'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stadium',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('capacity', models.PositiveIntegerField()),
                ('home_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='IplApp.franchise')),
            ],
        ),
    ]
